### ISSUE TITLE
could upstream/downstream terminology be used instead of parent/child ?

### ISSUE THREAD

**Issue by elf-pavlik** [w3c-ccg/zcap-ld#36]
https://w3c-ccg.github.io/zcap-ld/#terminology
> **parentCapability**
> The previous capability document on the chain, which is granting authority to this invocation document. In the case of the first delegated capability document, this points at the target. 

I'm looking into possibility of aligning [Solid Application Interoperability](https://solid.github.io/data-interoperability-panel/specification/) with Authorization Capabilities for Linked Data. In current version of SAI spec we already have notion of authorization delegation. We also have notion of defining what we grant access to based on inheritance like relationship in data - some *parent* data collection has *children* data members. In this situation it can be very tricky if someone gets confused when we address delegation chain and when we address inheritance within the data that authorization will apply to.

I wonder if ZCAP-LD could use *upstreamCapability* instead of *parentCapability*. I realize that this change wouldn't be justified by some spec possibly depending on ZCAP-LD. Still looking at current definition of *parentCapability* and discussing delegation chains, *upstreamCapability* seems pretty reasonable to me.

**Comment by TallTed** [comment]
Worth noting, some people get confused by upstream/downstream, especially if there's any reverse-flow of anything.  Push/pull have also proven problematic in the past.

I don't have an immediately better suggestion; just a suggestion to try and find one -- and/or very clearly describe and diagram the data flow(s), inheritance patterns, etc.

**Comment by dlongley** [comment]
> In this situation it can be very tricky if someone gets confused when we address delegation chain and when we address inheritance within the data that authorization will apply to.

I would suggest keeping your zcaps entirely separate from the objects they are applicable to. The latest implementations

**Comment by elf-pavlik** [comment]
ok thanks
